
version: '2.1'
services:
  docker-pull-through-cache:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
    image: ${DOCKER_REGISTRY:-home1oss}/pull-through-cache:2.6.1
    restart: always
    command: ["/etc/docker/registry/config.yml"]
    container_name: ${PULL_THROUGH_CACHE_HOSTNAME:-pull-through-cache.local}
    hostname: ${PULL_THROUGH_CACHE_HOSTNAME:-pull-through-cache.local}
    ports:
    - "${PULL_THROUGH_CACHE_PORT:-25000}:${PULL_THROUGH_CACHE_PORT:-25000}/tcp"
    environment:
    - PROXY=${PROXY}
    - PULL_THROUGH_CACHE_OF=${PULL_THROUGH_CACHE_OF}
    - PULL_THROUGH_CACHE_PORT=${PULL_THROUGH_CACHE_PORT:-25000}
    volumes:
    - volume-pull-through-cache:/var/lib/registry

networks:
  default:
    external:
      name: oss-network

volumes:
  volume-pull-through-cache: {}
