
version: '2.1'
services:
  docker-mirror-gcr:
    image: ${DOCKER_REGISTRY:-home1oss}/pull-through-cache:2.6.1
    restart: always
    command: ["/etc/docker/registry/config.yml"]
    container_name: ${PULL_THROUGH_CACHE_HOSTNAME:-registry-1.docker.io.local}
    hostname: ${PULL_THROUGH_CACHE_HOSTNAME:-registry-1.docker.io.local}
    ports:
    - "${PULL_THROUGH_CACHE_PORT:-25003}:${PULL_THROUGH_CACHE_PORT:-25003}/tcp"
    environment:
    - PROXY=${PROXY:-socks5://127.0.0.1:1080}
    - PULL_THROUGH_CACHE_OF=https://registry-1.docker.io
    - PULL_THROUGH_CACHE_PORT=${PULL_THROUGH_CACHE_PORT:-25003}
    volumes:
    - volume-mirror-hub:/var/lib/registry

networks:
  default:
    external:
      name: oss-network

volumes:
  volume-mirror-hub: {}
