
version: '2.1'
services:
  docker-mirror-gcr:
    image: ${DOCKER_REGISTRY:-home1oss}/pull-through-cache:2.6.1
    restart: always
    command: ["/etc/docker/registry/config.yml"]
    container_name: ${PULL_THROUGH_CACHE_HOSTNAME:-gcr.io.local}
    hostname: ${PULL_THROUGH_CACHE_HOSTNAME:-gcr.io.local}
    ports:
    - "${PULL_THROUGH_CACHE_PORT:-25004}:${PULL_THROUGH_CACHE_PORT:-25004}/tcp"
    environment:
    - PROXY=${PROXY:-socks5://127.0.0.1:1080}
    - PULL_THROUGH_CACHE_OF=https://gcr.io
    - PULL_THROUGH_CACHE_PORT=${PULL_THROUGH_CACHE_PORT:-25004}
    volumes:
    - volume-mirror-gcr:/var/lib/registry

networks:
  default:
    external:
      name: oss-network

volumes:
  volume-mirror-gcr: {}
